### ISSUE TITLE
Performance of Transfer Learning: Train encoder on different datasets

### ISSUE THREAD

**Issue by jianzongwu** [White-Link/UnsupervisedScalableRepresentationLearningTimeSeries#20]
Hi, I'm doing research on transfer learning of the representations learned by the encoder.

I have noticed that in your paper, only FordA dataset was used to perform transfer learning. I wonder have you tried other datasets to train the encoder and then train SVM on other UCR datasets? What's more, is there any patterns on pair of datasets which the target dataset benefits a lot from the training dataset through transfer learning? Another thinking is training the encoder on some of the datasets can get a better performance of transfer learning than others.

Thank you very much for discussing with me about those thinking. Your experience will help me a lot.

**Comment by White-Link** [comment]
Hi! Unfortunately, we did not perform transfer learning tests with another dataset than FordA, but we are interested in any additional transfer learning result for our method! I think that, as you mentioned, there should be more optimal datasets than others, in particular for datasets containing similar time series (for example, EEG). Another possibility is indeed to train the encoder on multiple datasets in order to increase its transfer learning ability.

**Comment by jianzongwu** [comment]
Thanks a lot for your answering!
This issue can be closed
