### ISSUE TITLE
How to treat incomplete time-series of unequal lengths

### ISSUE THREAD

**Issue by StatMixedML** [White-Link/UnsupervisedScalableRepresentationLearningTimeSeries#25]
Many thanks for the interesting repo and paper!

## Description
Going through the issues section of your repo, I would like to know how a data set with time series of unequal lenths and NAs should be treated.

## Example
Suppose we have a set of univariate time series, where each series is of varying length, also with some observations randomly missing. This is illustrated as follows

![image](https://user-images.githubusercontent.com/41187941/118483725-a9bf9280-b716-11eb-9238-626f7002eb30.png)

The NaNs are random and do not occur at the same point in time across time series. Also, each time series is of different length. Based on these issues https://github.com/White-Link/UnsupervisedScalableRepresentationLearningTimeSeries/issues/19 and https://github.com/White-Link/UnsupervisedScalableRepresentationLearningTimeSeries/issues/18 I am not sure how to deal with this problem. 

### Q1: 

In https://github.com/White-Link/UnsupervisedScalableRepresentationLearningTimeSeries/issues/18, you are stating

> Note that, in the case of time series of unequal lengths, we require to pad the series with NaNs up to max_length.

- Does this mean that say, if we have two time series, starting at the same date, one with _length1_ = 200, and the other _length2_ = 180 that we need to pad series2 with 20 NAs so as to recover the max_length of 200? 

- How shall we deal with this example if the time-series have different start dates? This has some implications since we cannot assume both having the same length, since one would start at say, January-2020, while the other starting at April-2020. Padding the second, shorter time series with 20 NAs would then force the model to assume them to have the same seasonality, even though they start differently.

### Q2:

In https://github.com/White-Link/UnsupervisedScalableRepresentationLearningTimeSeries/issues/19 you are stating

> We do not plan on supporting time series containing missing values, but we are interested in possible extensions to this end. As a workaround, you might for instance replace the missing values by zeros or removing them. This might be sufficient to learn satisfying representations for these datasets.

- Given the above example of time series with varying lengths and NAs, shall we impute the in-between missing values with 0 and in case the time series is shorter than the maximum length series, pad the series with NaNs up to max_length?
- What would be the difference in terms of representations if we padded the series with 0s up to max_length instead of NAs?
- Does your above statement imply that we should simply omit the NAs and then either pad the shorter series with NA or 0 up to max_length? If so, how can we ever approach to learn seasonalities with this? Say, for one arbitrary time-series, as below, we omit the missing values and put the ends together, which would be May-2020 and August-2020. For the model, this then is one complete time-series, even though we miss June-2020, July-2020. Also we assume that August-2020 directly follows May-2020.

In summary, these are the options:

- This is the original time-series, with some missing observations missing at random
![image](https://user-images.githubusercontent.com/41187941/118496252-3d4b9000-b724-11eb-82b2-1e755a165f43.png)

- Impute the missing values with 0s
![image](https://user-images.githubusercontent.com/41187941/118496024-0bd2c480-b724-11eb-95f6-fa063c81b77f.png)

- Drop the in-between NAs and create a new time-series by putting the ends together, risking that there is a jump (in red) due to the discontinuity and pad the missing observations at the end with Na up to max_length (orange)
![image](https://user-images.githubusercontent.com/41187941/118495706-bdbdc100-b723-11eb-99aa-2c54b0d7c88a.png)

- Drop the in-between NAs and create a new time-series by putting the ends together, risking that there is a jump (in red) due to the discontinuity and pad the missing observations at the end with 0 up to max_length (orange)
![image](https://user-images.githubusercontent.com/41187941/118495827-dcbc5300-b723-11eb-89de-300c5a2758f9.png)

**Comment by White-Link** [comment]
Hi, thanks again for your interest in our work and sorry for the late reply! Here is my attempt at answering your questions, please let us know if you have any other one.

## Q1

Indeed, all time series must be padded with NaNs up to the maximum length in the dataset. However, this is only a technical requirement as our method does not take into account temporality correspondences between time series and NaNs are never used in computations (they are only leveraged to determine the actual lengths of the time series). Thus, in your example, the starting dates of the time series do not matter with respect to our model.

In the case where you would want to take this temporality into account, you could merge univariate series starting at the same time as a single multivariate time series, but this raises the question of how to deal with NaNs to make the series coincide (we do not support multivariate series with non-simultaneous NaNs), as you pointed out, which brings us to the next question.

## Q2

I cannot provide a definite answer to these questions, but I can share some intuitions that remain to be verified in practice.

I would say that it depends on the significance of your missing values. If they are meaningful with respect to the observed phenomenon, then replacing them with zeros (or any out-of-distribution value) could probably do the trick. If they are not, at it seems to be the case in your application because of their randomness, I would avoid this workaround and try to replace them with plausible values, without joining ends as you propose since this amounts to introduce a potentially harmful temporal offset. You might consider using some kind of interpolation taking into account the seasonality of your dataset, or a more elaborate completion method for missing values in time series as it seems to be an active area of research.

**Comment by StatMixedML** [comment]
@White-Link Thanks for the clarifications!

I close the issue now.
