### ISSUE TITLE
Multivariate dataset s.t. each variable has a distinct value pattern

### ISSUE THREAD

**Issue by Huilin-Zhu** [White-Link/UnsupervisedScalableRepresentationLearningTimeSeries#28]
Hi, I am using your work to encode multivariate time series data generated from various sensors of a machine. The values patterns of these sensors are quite different from each other.  For example, one sensor would record temperature (continuous data), another sensor would record on/off status (0 or 1 data). In this case, is it suitable to train one encoder for all the sensors, or one encoder per sensor? Since it's a triplet loss model, I imagine that one encoder for all the sensors would suffice? Looking forward to hear your suggestions. Thank you!

**Comment by White-Link** [comment]
Hi, thank you for your interest in our work!

Since our triplet loss and encoding method are indeed generally applicable to multivariate time series, I would see no reason a priori to train an encoder per dimension. Thus, unless your data presents some particularity (different sampling rates over the dimensions, sensor data that cannot be normalized, resilience requirements for missing sensor data, etc.), I would recommend that you first train one encoder for all the sensors. Nonetheless, the best way to confirm this intuition is to try both alternatives.

Please let us know whether you have any other questions about our code or model!
