### ISSUE TITLE
Multi-GPU parallel training

### ISSUE THREAD

**Issue by xuchunyu123** [White-Link/UnsupervisedScalableRepresentationLearningTimeSeries#31]
Hello, after reading your code, I found that it is a single GPU training. If I want to train multiple GPUs in parallel, where can I change the code to achieve this effect, looking forward to your reply

**Comment by White-Link** [comment]
Hi, indeed this code does not support multi-GPU training. Unfortunately, we do not plan on adding new features to this code, as this would require significant changes to its core architecture to make it comply with today's standard.

Nonetheless, a cheap, though not ideal, solution could be to wrap the encoder (instance of `CausalCNNEncoder`) with [a `torch.nn.DataParallel` container](https://pytorch.org/docs/stable/generated/torch.nn.DataParallel.html) so that it automatically distributes its computations over several GPUs. However, we have not tested this yet so we cannot guarantee that it will properly work and remain efficient.
