### ISSUE TITLE
Training fails on samples of unequal length

### ISSUE THREAD

**Issue by 3dde** [White-Link/UnsupervisedScalableRepresentationLearningTimeSeries#34]
Hi, I'm having problems executing the training on a dataset with samples of different lengths.
My hyperparameters:
```
batch_size = 5,
channels = 40,
compared_length = 225000,
depth = 10,
in_channels = 6,
nb_steps = 1500,
kernel_size = 3,
penalty = null,
early_stopping = null
lr = 0.001,
nb_random_samples = 10,
negative_penalty = 1,
out_channels = 320,
reduced_size = 160
```

As described in other issues as well, I have transformed the dataset to be in the shape of (<number of samples>, <number of parameters per sample>, <length of samples>). I have also padded all samples to the length of the longest sample with NaNs. Interestingly, the training works on the same dataset when using two samples of the same length. With this configuration, however, and using 57 samples, I get the following error:

```
Traceback (most recent call last):
  File "/home/user/Dokumente/models/USRLTS/script.py", line 102, in <module>
    encoder.fit_encoder(train, save_memory=True, verbose=True)
  File "/home/user/Dokumente/models/USRLTS/scikit_wrappers.py", line 263, in fit_encoder
    loss = self.loss_varying(
  File "/home/user/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/Dokumente/models/USRLTS/losses/triplet_loss.py", line 238, in forward
    lengths_pos[j] = numpy.random.randint(
  File "numpy/random/mtrand.pyx", line 782, in numpy.random.mtrand.RandomState.randint
  File "numpy/random/_bounded_integers.pyx", line 1334, in numpy.random._bounded_integers._rand_int64
ValueError: low >= high
```

I have tried diagnosing this and found a couple of interesting things:
- The batch shape given to the "TripletLossVaryingLength" loss class in triplet_loss.py is (5,6,3434578) even though I padded all samples to a length of 4293222
- The lengths calculated for each batch (lengths_batch) and lengths_samples in lines 210-221 of triplet_loss.py are all 0 (this is causing the error)

However, I don't understand why the calculated length is 0, as it is subtracting the number of values being NaNs, and I have only padded the end of the samples with NaNs. Is there anything I am missing?

**Comment by White-Link** [comment]
Hello, sorry for the late answer. I hope you could find a solution to your issue.

After checking the code, I do not think the problem comes from the code. The shape of the data is not altered from the call to [`fit` in `TimeSeriesEncoderClassifier`](https://github.com/White-Link/UnsupervisedScalableRepresentationLearningTimeSeries/blob/master/scikit_wrappers.py#L301) to the [forward of the loss](https://github.com/White-Link/UnsupervisedScalableRepresentationLearningTimeSeries/blob/master/losses/triplet_loss.py#L197). The next lines also correctly compute the length of each element in the batch and in the dataset.

Therefore, I believe the issue comes from your side. Please let me know otherwise.

**Comment by 3dde** [comment]
Thanks for your answer! The error was indeed my fault, my normalization step produced nonsense data. However, I'm having another issue now (see #35)
