### ISSUE TITLE
encode_window with varying length data

### ISSUE THREAD

**Issue by 3dde** [White-Link/UnsupervisedScalableRepresentationLearningTimeSeries#35]
I am using the same configuration as in #34, except using a batch size of 1. I have padded all input data with nans to the same length. The fitting of the encoder works without problems. However, I get the following error when using encode_window on my test data:

`RuntimeError: Only zero batch or zero channel inputs are supported, but got input shape: [1, 6, 1, 0]`

For context, my data is 6-dimensional. Should the test data not be multiple samples? Or should they not be padded?

Thanks in advance!

**Comment by White-Link** [comment]
Hello, thanks for spotting this issue. It should be solved by now; otherwise please let me know.

Sliding windows may include series full of NaNs which were not considered in the code. Now it should output NaNs as well. Note that this is a quick fix which may be inefficient if your series has many missing values.

**Comment by 3dde** [comment]
Thank you so much for the quick fix!
